version: "3.3"

services:
  web:
    build:
      context: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
      python3 manage.py migrate &&
      gunicorn --bind 0.0.0.0:8000 demo.wsgi:application"
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`35.184.160.126`)"
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  traefik:
    image: traefik
    ports: 
      - 80:80
      - 8080:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
